# Generated by Django 3.2.5 on 2021-08-11 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_oderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items_related', to='store.order'),
        ),
    ]
