# Generated by Django 3.2.5 on 2021-08-20 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_delete_itemsaler'),
        ('store', '0009_auto_20210818_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='saler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.saler'),
        ),
    ]
