# Generated by Django 3.2.5 on 2021-08-20 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_rename_user_product_profileshop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='profileShop',
            new_name='profile_shop',
        ),
    ]
