# Generated by Django 3.2.5 on 2021-08-21 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saler_channel', '0003_rename_saler_profileshop_user'),
        ('store', '0019_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='profile_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='saler_channel.profileshop'),
        ),
    ]
