# Generated by Django 3.2.5 on 2021-09-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_auto_20210929_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
