# Generated by Django 3.2.5 on 2021-09-29 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_category_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categorie',
        ),
    ]
