# Generated by Django 3.2.5 on 2021-08-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saler',
            name='description',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='saler',
            name='name_store',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
