# Generated by Django 3.2.5 on 2021-08-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210819_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saler',
            name='description',
            field=models.CharField(default='', max_length=250, null=True),
        ),
    ]
