# Generated by Django 3.2.5 on 2021-08-20 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_saler_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemSaler',
        ),
    ]
