# Generated by Django 3.2.5 on 2021-08-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saler_channel', '0005_alter_profileshop_name_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileshop',
            name='avatar',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
